### PR TITLE
Adding Edge & WebKit implementation status links

### PR DESCRIPTION
**Pull request by aarongustafson**
I also alphabetized the links.

***
[Preview](https://s3.amazonaws.com/pr-preview/aarongustafson/manifest/adding-edge-implementation-status.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/manifest/9642178...aarongustafson:6561007.html)

### CODE REVIEW

**Comment by aarongustafson** [comment]
I just realized my W3C & Github accounts were not connected. Fixed.

**Comment by kenchris** [comment]
Ok I cannot mark as non substantive.. @anssik ?

**Comment by anssiko** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by anssiko** [comment]
@kenchris, done.

(FTR, the awkwardly named tool to do this is at https://labs.w3.org/hatchery/repo-manager/)

**Pull request merged**
