### PR TITLE
chore: add Rob Dolin as co-editor

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/manifest/add_rob.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/manifest/9642178...f286ba0.html)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@dontcallmedom having IPR issues here as well... but we didn't rename the repo, I don't think.

**Comment by dontcallmedom** [comment]
@marcoscaceres Mozilla has not [rejoined the Web Platform Working Group](https://www.w3.org/2004/01/pp-impl/83482/status), hence the IPR failure :(

**Comment by kenchris** [comment]
Microsoft, you mean :)

**Comment by kenchris** [comment]
Or it is because of @marcoscaceres ?

**Comment by dontcallmedom** [comment]
the latter (since the PR comes from @marcoscaceres )

That being said, this is obviously an editorial change, so ignoring the IPR checker is fine here

**Comment by dontcallmedom** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by marcoscaceres** [comment]
@dontcallmedom I had a feeling that might be the case... I'll email dbaron.

**Comment by kenchris** [comment]
@anssiko we also don't seem to have joined, can you look into that?

**Comment by anssiko** [comment]
Welcome to the team @robdolinms!

@kenchris, I informed our AC rep.

**Comment by marcoscaceres** [comment]
heh, our pull requests are all IPR suspect and derelict 😼

**Comment by aarongustafson** [comment]
Yay!

**Comment by anssiko** [comment]
@kenchris ...and Intel has rejoined the WG, so no more IPR failures. Was due to the recent recharter that required everyone to rejoin the WG.

**Comment by RobDolinMS** [comment]
Thank you very much @marcoscaceres @kenchris @anssiko  I'm honored to be a part of team

**Comment by LJWatson** [comment]
Sorry to throw a spanner in the works, but editors need to be [appointed by the WG chairs](https://www.w3.org/2017/Process-20170301/#general-requirements). marcoscaceres and/or @RobDolinMS could you ping team-webplatform@w3.org with a request to be added as editor for this spec? Thanks.

**Comment by marcoscaceres** [comment]
Sure, will do.

**Comment by marcoscaceres** [comment]
Email sent.

**Comment by LJWatson** [comment]
Thanks @@marcoscaceres. Spanner has been removed from the works :) Welcome @RobDolinMS!

**Comment by marcoscaceres** [comment]
@dontcallmedom pinged dbaron, but he said we had rejoined and joined and pointed me to: https://www.w3.org/2000/09/dbwg/details?group=83482&public=1&order=org#_MozillaFoundation 

I'm there. Is there still a mismatch somewhere?

**Comment by dontcallmedom** [comment]
the fact that you're still listed in DBWG is because we're in the 45 days grace period; the authoritative list of organizations who have made the IPR commitments is https://www.w3.org/2004/01/pp-impl/83482/status and Mozilla is not there, which to the best of my knowledge means Mozilla still needs to rejoin.

**Comment by marcoscaceres** [comment]
Thanks! will let David know.

**Pull request merged**
