### PR TITLE
Address privacy issue with start_url

### LINKED ISSUE #399: Privacy Review: handle start_url tracking
To summarize @npdoty comments in https://lists.w3.org/Archives/Public/public-privacy/2015JanMar/0117.html there are concerns about `start_url` containing special ids or simply something that hints that the user is coming from a homescreen application. This is fingerprinting/privacy sensitive information that the user might not be aware of.

I think the issue of people doing `start_url: 'index.html?from_homescreen'` is something we might want to mention in the spec but I don't think we should encourage browsers to prevent this because it is clearly something websites want for various reasons (mostly statistics).

However, I am concerned about having `start_url: 'index.html?$GUUID'` because it is a way to track the user without them being aware of it. I'm not sure what the spec should say or the browsers could do. Maybe we could recommend showing the `start_url` to the user and allow them to edit it?

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #399 

This change (choose at least one, delete ones that don't apply):

* Adds new normative recommendations or optional items
* Makes editorial changes (changes informative sections, or changes normative sections without changing behavior)

Implementation commitment (delete if not making normative changes):

 * This is an authoring requirement.

Commit message:
Attempt to address #399

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/pull/1029.html" title="Last updated on Jan 20, 2022, 1:37 AM UTC (a1955e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/1029/f8d326b...a1955e7.html" title="Last updated on Jan 20, 2022, 1:37 AM UTC (a1955e7)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@npdoty, can you please take a look? Would this change satisfy PING?

**Comment by aarongustafson** [comment]
This looks good to me. Thanks @marcoscaceres!

**Comment by lknik** [comment]
@marcoscaceres Looks ok, "we're doing something" :)

**Review by kenchris — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Ok, let's take it and get more feedback before we go to CR as part of horizontal reviews.

**Comment by dmurph** [comment]
Adding myself as reviewer for searching purposes

**Pull request merged**
