### PR TITLE
Misc chores

### PR DESCRIPTION
**Pull request by mgiuca**
***
<a href="https://pr-preview.s3.amazonaws.com/mgiuca/manifest/pull/671.html" title="Last updated on May 7, 2018, 6:50 AM GMT (e0b36ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/671/32dd32c...mgiuca:e0b36ae.html" title="Last updated on May 7, 2018, 6:50 AM GMT (e0b36ae)">Diff</a>

### CODE REVIEW

**Comment by mgiuca** [comment]
I think I used to be able to just push things like this to the repo without review (and I have done so in the past). Now I get a security error, so bunching them up into a review.

**Comment by marcoscaceres** [comment]
Added a bit of branch protection, as we have quite a few people with write access.

**Comment by marcoscaceres** [comment]
(never hurts to get review tho, as long as we are speedy about it)

**Comment by mgiuca** [comment]
Fair enough. Can't complain about a 30-second review turn-around time :) :1st_place_medal:

**Pull request merged**
