### PR TITLE
Set the manifest request's `destination`.

### PR DESCRIPTION
**Pull request by mikewest**
This change (choose one):

* [ ] Breaks existing normative behavior (please add label "breaking")
* [x] Adds new normative requirements
* [ ] Adds new normative recommendations or optional items
* [ ] Makes only editorial changes (only changes informative sections, or
  changes normative sections without changing behavior)
* [ ] Is a "chore" (metadata, formatting, fixing warnings, etc).

Commit message:

Manifest's fetching algorithm currently defines the request's `initiator` as "manifest",
but neglects to set the `destination`. This patch corrects this minor oversight.

***

### :boom: TypeError: Cannot read property 'owner' of null :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 30, 2020, 5:31 AM UTC)_.

<details>
<summary>More</summary>

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/manifest%23829.)._
</details>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
I wonder if this does fall under a normative requirement. I imagine all UAs probably do the right thing, but might be worth checking the outbound `request`s.

**Comment by mikewest** [comment]
It's "normative". :)

The value does show up in the `Sec-Fetch-Dest` header (which is why @jugglinmike pointed me to this in the first place), and in the `destination` field of an outgoing Manifest request that's intercepted by a Service Worker. But it's also pretty clearly an oversight in the spec implied by the `initiator` value, and it looks like both Chrome and Firefox (https://searchfox.org/mozilla-central/source/dom/fetch/InternalRequest.cpp#353) already have the right behavior.

**Comment by mikewest** [comment]
I'd be totally fine with you waiting to land this until we have a `Sec-Fetch-Dest` test in place, or if you'd like to write a Service Worker test... The [manifest coverage in WPT](https://github.com/web-platform-tests/wpt/search?q=%22rel%3Dmanifest%22&unscoped_q=%22rel%3Dmanifest%22) looks pretty much nonexistent. :(

**Comment by marcoscaceres** [comment]
oh, the underlying repo vanished - was being lazy to re-trigger the checks by closing/reopening. I'll add this to the spec now.

**Pull request closed without merging**
