### PR TITLE
Added missing space.

### PR DESCRIPTION
**Pull request by tomayac**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Appreciate these fixes, but tidy will probably trash them. It might also cause merge conflicts with the big changes that Kenneth is making. Can we please hold on these?

**Comment by tomayac** [comment]
OK, makes sense. Do you want me to close the Pull Request or leave it open until Kenneth's changes are in?

**Comment by marcoscaceres** [comment]
No, leave it - it's all good. I just checked with tidy locally and they seem to be holding ok... but let's let @kenchris finish https://github.com/w3c/manifest/pull/613 ... I'm already making his life super hard with markup fixes, so worried about adding any additional pain 😸

**Comment by kenchris** [comment]
Mine was merged, if you want to have another look :)

**Comment by marcoscaceres** [comment]
This no longer applies - but appreciate the help @tomayac!

**Pull request closed without merging**
