### PR TITLE
Chaals patch 1

### PR DESCRIPTION
**Pull request by chaals**
err, if you are going to do something, at least make it well formed

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@chaals, thanks again. Can I kindly ask you to merge your commits into a single one and provide a slightly better commit message describing the change? That helps keep our commit history clean.  If you need instructions on how to do that, happy to provide.

**Comment by chaals** [comment]
Yeah, sorry...
Instructions would be appreciated (I'm somewhat distracted by OzeWAI at the moment)

**Comment by marcoscaceres** [comment]
(I'm assuming your are doing this from the command line, if not... it's ok, just stop and I can try to do it fix it.... otherwise...)

Read the instructions first all the way through, specially if you've never done a rebase before. Your text editor will pop up a few times, which you might not be expecting. It's normal :)

The following will open up your text editor: 
```
git rebase -i HEAD~2
```
There you will see:

```git
pick commithash more work...
pick commithash oops...
```

change the second "pick" to "f" and the first to "r", like so (example only, keep the commit hash you have!!). The will tell git that the second commit is a "fixup" of the first, and that you want to rewrite the commit message for the first commit. So, it should now look like this: 

```git
r commithash more work...
f commithash oops...
```

Save, close your editor. Your editor will open up again! But this time you will "more work...". Rewrite the message to better describe the change. Save and quit your editor.

Now, finally, do: 
```
git push -f  
```

**Comment by marcoscaceres** [comment]
OzeWAI... you coming to Melbourne after??????

**Comment by kenchris** [comment]
Any progress on merging these commits?

**Comment by marcoscaceres** [comment]
Will take a look ASAP. Fixing some ReSpec fallout first! Shouldn't take long.

**Pull request merged**
