### PR TITLE
Drop .json as standard file ext. (closes #381)

### LINKED ISSUE #381: .json in MIME registration is causing problems.
See: 
https://github.com/jshttp/mime-db/commit/078ed4e8e6695ce934e766069f35f97cf8dedf99

Should probably only register `.webmanifest` as the "standard" file extension.

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by alrra** [comment]
@marcoscaceres You should also update the examples: [1](https://github.com/w3c/manifest/blob/b09c099f7007a0c0eb737af90161268905ec810f/index.html#L185), [2](https://github.com/w3c/manifest/blob/b09c099f7007a0c0eb737af90161268905ec810f/index.html#L1602)).

**Comment by marcoscaceres** [comment]
@alrra done :)

**Comment by mounirlamouri** [comment]
What is the rationale behind this change?

**Comment by mounirlamouri** [comment]
Scratch that, I found the issue.

**Pull request merged**
