### PR TITLE
Defined identity based on manifest URL (closes #272)

### LINKED ISSUE #272: Define identity of a web app.
* what identifies an app? An origin?  
 * how does one update the app? 
 * what happens if the scope changes?

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by kenchris** [comment]
lgtm... though spelling issue :) yes, again! "identiy" :)

**Comment by marcoscaceres** [comment]
Spelling is hard.

**Comment by marcoscaceres** [comment]
Fixed commit message typo

**Comment by marcoscaceres** [comment]
Fixed another typo

**Pull request merged**
