### PR TITLE
deprecate gh-pages in favor of echidna

### LINKED ISSUE #492: Drop gh-pages branch
As we are using echidna, we don't need to be publishing gh-pages.

### PR DESCRIPTION
**Pull request by patrickkettner**
fixes #492

removed images because `independent_policies.svg` isn't used anywhere, and I assumed that Echidna would host `manifest-src-directive.svg`.

as an aside - I attempted to push this branch to the w3c repo directly, but got a 403. Not sure if that is whats supposed to happen

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Looks like it needs a rebase. 

> as an aside - I attempted to push this branch to the w3c repo directly, but got a 403. Not sure if that is whats supposed to happen

No, that should have worked...

**Comment by patrickkettner** [comment]
> Looks like it needs a rebase.

it is based on the last commit in gh-pages. What should I rebase against?

> No, that should have worked...

¯\_(ツ)_/¯

image

**Comment by siusin** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by marcoscaceres** [comment]
Argh! sorry @patrickkettner. I had accidentally set your permission to read only.

**Comment by patrickkettner** [comment]
@marcoscaceres permissions have been fixed, I pushed to a branch on this repo :yay:

also, I rebase

finally - thanks to @RobDolinMS for pinging me constantly to get this very simple change in. my inbox accidentally filed them in a way that made me never see them and he has been ridiculously patient with me :]

**Comment by marcoscaceres** [comment]
np, I also kept causing conflicts :) I'll rebase the existing PRs on the new "master" branch.

**Pull request merged**
