### PR TITLE
Address timeless' review comments

### PR DESCRIPTION
**Pull request by anssiko**
https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0794.html

### CODE REVIEW

**Comment by kenchris** [comment]
lgtm

**Comment by marcoscaceres** [comment]
Thanks for catching this! I'm not subscribed to the mailing list :)

**Comment by marcoscaceres** [comment]
@anssiko, can you please let Josh know you've made the changes. If we still have his attention, it would be great if he could do the rest of the doc :) Ping me if he posts again to the list - I'm happy to handle the editorial changes (unless you are also happy to do them).

**Comment by anssiko** [comment]
@marcoscaceres I was guessing you may not be subscribed to the list :-) I responded to Josh on the list: https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0914.html

Now that I'm at it, I'm happy to address the rest of the feedback too.

**Pull request merged**
