### PR TITLE
Update manifest example to be consistent

### PR DESCRIPTION
**Pull request by rmacklin**
The `name`, `description`, and `short_name` in this manifest example were describing a donation app, while the other attributes (`scope`, `start_url`, `screenshots`) were for a racing game. This updates the `name`, `description`, and `short_name` to refer to the racing game, which makes the manifest consistent internally within itself and consistent externally with the [manifest in explainer.md].

[manifest in explainer.md]: https://github.com/w3c/manifest/blob/0707d4a1894b96b0c42e9cd4f9761f1bf90c88b8/explainer.md#a-typical-manifest

***
<a href="https://pr-preview.s3.amazonaws.com/rmacklin/manifest/pull/635.html" title="Last updated on Jan 9, 2018, 7:38 AM GMT (7313ca5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/635/0707d4a...rmacklin:7313ca5.html" title="Last updated on Jan 9, 2018, 7:38 AM GMT (7313ca5)">Diff</a>

### CODE REVIEW

**Comment by kenchris** [comment]
As you made the change to donation, will you take this one @marcoscaceres

**Comment by marcoscaceres** [comment]
Yep, but when I’m back from 🏖 next week.

**Comment by rmacklin** [comment]
👍  This is obviously a non-substantive change, so take your time. Another way to take this would of course be to switch the other manifest fields to seem consistent for a donation app. I just went with this to match the `explainer.md` example since that was the easiest change. While not super important, I do think having the fields be consistent would be an improvement (when I was reading the spec, seeing the "racer" `scope` and `start_url` made me do a bit of a double take).

**Comment by marcoscaceres** [comment]
Marked as non substantive for IPR from ash-nazg.

**Pull request merged**
