### PR TITLE
Change platform android by play in exemple

### PR DESCRIPTION
**Pull request by bastienmoulia**
To be consistent with https://github.com/w3c/manifest/wiki/Platforms

***
[Preview](https://s3.amazonaws.com/pr-preview/bastienmoulia/manifest/patch-1.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/manifest/2f5edbf...bastienmoulia:5bf60c7.html)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by marcoscaceres** [comment]
@mgiuca, sorry to assign you; just want to make sure that this is correct as per what is used in Chrome.

**Comment by marcoscaceres** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by mgiuca** [comment]
Whoops... I only just saw this 😳.

This looks good. Can you rebase, then I'll be happy to merge.

**Pull request closed without merging**
