### PR TITLE
editorial: enable MDN annotations

### PR DESCRIPTION
**Pull request by marcoscaceres**
This change (choose one):

* [ ] Breaks existing normative behavior (please add label "breaking")
* [ ] Adds new normative requirements
* [ ] Adds new normative recommendations or optional items
* [x] Makes only editorial changes (only changes informative sections, or
  changes normative sections without changing behavior)
* [ ] Is a "chore" (metadata, formatting, fixing warnings, etc).

Commit message:
Adds MDN annotation for various things, like so:

Screenshot 2019-07-18 17 48 04

Note: this only covers the BIP interface at the moment, as well as the CSS rule.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/pull/772.html" title="Last updated on Jul 18, 2019, 7:52 AM UTC (128bd03)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/772/3223baf...128bd03.html" title="Last updated on Jul 18, 2019, 7:52 AM UTC (128bd03)">Diff</a>

### CODE REVIEW

**Comment by kenchris** [comment]
Very nice

**Comment by marcoscaceres** [comment]
✨Sprinkle liberally on ReSpec specs ✨

**Comment by kenchris** [comment]
Edge Mobile is either WebKit or Chromium, so why is there only one?

**Comment by marcoscaceres** [comment]
Dunno... data is coming from MDN. We would need to ask them.

**Comment by marcoscaceres** [comment]
(or the data is out of date... which is likely... don't know how often they refresh the data or how it's done)

**Comment by torgo** [comment]
Hmmmm... @travisleithead ?

**Pull request merged**
