### PR TITLE
Removed six occurrences of superfluous spaces after quotes.

### PR DESCRIPTION
**Pull request by tomayac**

### CODE REVIEW

**Comment by kenchris** [comment]
Lgrm

**Comment by anssiko** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by anssiko** [comment]
Thanks!

(I'm wondering whether this was a tidy bug, since it was reoccurring.)

**Comment by marcoscaceres** [comment]
@anssiko, I think it was caused by a previous version of tidy (< 5.4), and then the new version didn't auto fix it. However, the manual fixes actually hold in the newer version of tidy - so these are great.

**Pull request merged**
