### PR TITLE
Export WebAppManifest dfn as a dictionary

### PR DESCRIPTION
**Pull request by jyasskin**
This change (choose one):

* [ ] Breaks existing normative behavior (please add label "breaking")
* [ ] Adds new normative requirements
* [ ] Adds new normative recommendations or optional items
* [ ] Makes only editorial changes (only changes informative sections, or
  changes normative sections without changing behavior)
* [X] Is a "chore" (metadata, formatting, fixing warnings, etc).

Commit message:

Export WebAppManifest dfn as a dictionary.

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/manifest/pull/767.html" title="Last updated on Jun 24, 2019, 6:36 PM UTC (8bd740a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/767/3223baf...jyasskin:8bd740a.html" title="Last updated on Jun 24, 2019, 6:36 PM UTC (8bd740a)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
We are looking at ditching the WebIDL from the spec in favor of Infra types. @jyasskin, I can still try to export something useful for you though... I guess you just need the top level object? Can you give us a bit more context where you want to reference it?

**Comment by jyasskin** [comment]
An Infra type would be at least as good. I want to use this to represent the parsed form of the App Manifest inside a Bundle (https://wicg.github.io/webpackage/draft-yasskin-wpack-bundled-exchanges.html#manifest-section).

**Comment by marcoscaceres** [comment]
Latest ReSpec should be automatically adding the right `data-dfn-type` types. However, I'm still working on moving the spec to using Infra types instead of IDL. Sorry it's taking a while tho... big spec change, limited cycles :(

**Comment by jyasskin** [comment]
In view-source:https://www.w3.org/TR/appmanifest/, I see

```html
<dfn data-dfn-for="" data-dfn-type="dfn" id="dom-webappmanifest" data-idl="dictionary" data-title="WebAppManifest"><code>WebAppManifest</code></dfn>
```
```html
<dfn data-dfn-for="webappmanifest" data-dfn-type="dfn" id="dom-webappmanifest-start_url" data-idl="field" data-title="start_url" data-type="USVString"><code>start_url</code></dfn>
```

Maybe you just need to regenerate the TR/ version from a later respec?

I totally understand the delay in switching to Infra types. Just let me know when that's done, and I'll update any spec text I've written that points to the IDL types.

**Comment by marcoscaceres** [comment]
Yeah, the definitions are picked up from TR. I guess we can just put up a new version with all the exports, but just be mindful that links might break when we do the republish. Will try not to break things... but if things break let me know.

**Comment by marcoscaceres** [comment]
Will try to republish gh-pages in a few mins.

**Comment by marcoscaceres** [comment]
Sorry, generating the spec is currently timing out on the w3c server. Filed: https://github.com/w3c/echidna/issues/675  

Will try to get it republished manually on TR in the meantime. Will report back once it's up.

**Comment by aarongustafson** [comment]
Let me know if I can help in any way.

**Comment by marcoscaceres** [comment]
Ok, it generated. All good. Shepherd should hopefully have picked it up by now.

**Comment by jyasskin** [comment]
Yep, it’s finding the right links. Thanks!

**Pull request closed without merging**
