### PR TITLE
Use `https://` where possible

### PR DESCRIPTION
**Pull request by alrra**
Don't forget to also change the link from the description of the repository:

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Awesome! :+1: you confirmed all those work, right?

**Comment by marcoscaceres** [comment]
@darobin, can you change the link for the repo please?

**Comment by alrra** [comment]
> you confirmed all those work, right? 

@marcoscaceres I checked 2 times, and only changed the ones that do support HTTPS and also do not show [that annoying prompt](https://cloud.githubusercontent.com/assets/1223565/7035354/3ca60afa-dd90-11e4-9b3d-e48cae3f7e16.png).

**Comment by marcoscaceres** [comment]
Thanks @alrra! that's great.

**Comment by marcoscaceres** [comment]
Seems to be up already: http://www.w3.org/TR/2015/WD-appmanifest-20150407/

**Comment by alrra** [comment]
> Don't forget to also change the link from the description of the repository:

> 

@darobin @marcoscaceres :arrow_up:

**Comment by darobin** [comment]
Done

**Pull request merged**
