### PR TITLE
WebAppManifest itself should be top-level (for="")

### PR DESCRIPTION
**Pull request by jyasskin**
This change (choose one):

* [ ] Breaks existing normative behavior (please add label "breaking")
* [ ] Adds new normative requirements
* [ ] Adds new normative recommendations or optional items
* [ ] Makes only editorial changes (only changes informative sections, or
  changes normative sections without changing behavior)
* [x] Is a "chore" (metadata, formatting, fixing warnings, etc).

Commit message: WebAppManifest itself should be top-level (for="")

***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/manifest/pull/785.html" title="Last updated on Sep 21, 2019, 2:13 AM UTC (9b0df94)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/785/6851b18...jyasskin:9b0df94.html" title="Last updated on Sep 21, 2019, 2:13 AM UTC (9b0df94)">Diff</a>

### CODE REVIEW

**Comment by jyasskin** [comment]
I can't read. Never mind.

**Comment by jyasskin** [comment]
Some recent change led to the definition being:

```html
<section data-dfn-for="WebAppManifest" data-link-for="WebAppManifest" id="webappmanifest-dictionary"> ...
  <dfn data-dfn-type="dictionary" data-export="" id="dom-webappmanifest" data-idl="dictionary" data-title="WebAppManifest"><code>WebAppManifest</code></dfn>
...
```

And Bikeshed complains on `{{WebAppManifest}}` with `No 'idl' refs found for 'WebAppManifest' with for='None'.`

So I think this change is useful again.

**Comment by marcoscaceres** [comment]
Need to check why it's being weird... what we had originally should have worked, but let's go with this for now.

**Comment by marcoscaceres** [comment]
Cc @sidvishnoi ... can you help use investigate what's going on:

`WebAppManifest` is a dictionary, but in xref it's showing up as `{{WebAppManifest/WebAppManifest}}` for how to cite it.

**Pull request merged**
