### PR TITLE
Removed six occurrences of superfluous spaces after quotes.

### PR DESCRIPTION
**Pull request by tomayac**

### CODE REVIEW

**Comment by tomayac** [comment]
I have just connected my W3C account (```tsteiner```) and my GitHub account (```@tomayac```).

**Comment by kenchris** [comment]
Revalidate still complains: tomayac is unknown, they need to link their Github account with a W3C account

**Comment by kenchris** [comment]
@anssik?

**Comment by tomayac** [comment]
screen shot 2017-09-22 at 12 28 06

**Comment by anssiko** [comment]
It takes a while to propagate the changes I think. Now merged.

**Comment by marcoscaceres** [comment]
Tidy might add these back in🤓

**Pull request merged**
