### PR TITLE
[Explainer] Fix cralwers -> crawlers typo (#531)

### PR DESCRIPTION
**Pull request by RobDolinMS**
Signed-off-by: Rob Dolin <robdolin@microsoft.com>

### CODE REVIEW

**Comment by RobDolinMS** [comment]
@marcoscaceres (or another maintainer), please merge this one-line fix of a typo if it looks good to you.  

Also, if I need to do something for the automated IPR check, please let me know.  
(Microsoft is a member of the W3C Web Platform WG.)

**Comment by kenchris** [comment]
@marcoscaceres how to deal with the ipr issue?

**Comment by marcoscaceres** [comment]
@RobDolinMS, re IPR issue, can you check that you are actually a member of the Web Platform Working Group. You might need to ping whomever is the AC representative for Microsoft at the W3C (not sure who it is tho).

@dontcallmedom, could you kindly check @RobDolinMS membership status, etc.?

**Comment by dontcallmedom** [comment]
@marcoscaceres [Microsoft hasn't rejoined the group](https://www.w3.org/2004/01/pp-impl/83482/status) yet, so pull requests from Microsoft employees will be flagged by the repo manager.

In this case, this was clearly a non-substantive pull request, so you can hit the "mark as non-substantive" button from the repo manager to clear the failure.

**Comment by marcoscaceres** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by marcoscaceres** [comment]
Ok, @dontcallmedom thanks for checking! 

@RobDolinMS and other Microsofties, could you please join the group. Things like the screenshots member are largely attributed to you.

**Comment by RobDolinMS** [comment]
I understand from @MichaelChampion that paperwork for Microsoft to re-join the Web Platform WG is in-progress

**Pull request merged**
