### PR TITLE
Make Service Worker registration work properly (don't use outdated steps)

### LINKED ISSUE #789: Service worker installation uses an algorithm (Start Register) that doesn't exist in SW spec
> Invoke [Start Register](https://www.w3.org/TR/appmanifest/#dfn-start-register) with scope and src members of the registration, a new promise, client, manifest URL, plus the type and update_via_cache members of the registration, in which case the state of the settled promise determines whether the installation succeeded or not.

There is no "Start Register" in the SW spec. As far as I can tell, the nearest thing would be to simply invoke the [`register()`](https://www.w3.org/TR/service-workers-1/#navigator-service-worker-register) method.

I'm also not sure why this method would (ever) have taken the manifest URL. If we can avoid passing the manifest URL, then we don't need to store it in this algorithm.

Also note that this feature doesn't seem to have been implemented by any user agent, so it is considered "at risk" (though I still believe it would be useful which is why I haven't pushed to deleted it yet).

### PR DESCRIPTION
**Pull request by mgiuca**
This change (choose one):

* [ ] Breaks existing normative behavior (please add label "breaking")
* [ ] Adds new normative requirements
* [ ] Adds new normative recommendations or optional items
* [X] Makes only editorial changes (only changes informative sections, or
  changes normative sections without changing behavior)
* [ ] Is a "chore" (metadata, formatting, fixing warnings, etc).

Commit message:

Make Service Worker registration work properly (don't use outdated steps).

Closes #789.

***
<a href="https://pr-preview.s3.amazonaws.com/mgiuca/manifest/pull/792.html" title="Last updated on Nov 12, 2019, 8:21 AM UTC (771b8c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/manifest/792/e46df46...mgiuca:771b8c5.html" title="Last updated on Nov 12, 2019, 8:21 AM UTC (771b8c5)">Diff</a>

### CODE REVIEW

**Comment by mgiuca** [comment]
The upstream PR has now merged, so this PR's delta is correct.

**Comment by kenchris** [comment]
Well Jeffrey (talked at TPAC) says to please not do that as he is going to use that innWeb Packaging which uses web app manifest

**Comment by kenchris** [comment]
@jyasskin could you comment?

**Comment by marcoscaceres** [comment]
Sure, but the multi-implementer problem remains. Not sure at this point we want to support this in Gecko, but need to check if WebKit supports it.

**Comment by jyasskin** [comment]
We might use the `serviceworker` field to have navigation to a web package automatically install its service worker before the start page loads, but I think we can re-add the field if/when we do that. It won't hurt us to remove it until then.

**Comment by marcoscaceres** [comment]
Ok, let's proceed with the plan to remove it... we can always bring it back.

**Comment by mgiuca** [comment]
Oops, thanks for closing this out.

**Pull request merged**
